INSERT INTO room_users (room_id, user_id) VALUES (1, 1);
INSERT INTO room_users (room_id, user_id) VALUES (1, 2);
INSERT INTO room_users (room_id, user_id) VALUES (1, 3);
INSERT INTO room_users (room_id, user_id) VALUES (2, 3);
INSERT INTO room_users (room_id, user_id) VALUES (2, 4);
INSERT INTO room_users (room_id, user_id) VALUES (2, 5);
INSERT INTO room_users (room_id, user_id) VALUES (3, 5);
INSERT INTO room_users (room_id, user_id) VALUES (3, 6);
INSERT INTO room_users (room_id, user_id) VALUES (3, 7);
