### get landing page
GET http://localpost:8080/ HTTP/1.1
###
GET https://obscure-harbor-31858.herokuapp.com/tests HTTP/1.1

###
GET http://localhost:3001/api/games/round/?room_id=1



###
GET http://localhost:3001/api/games/hand/?game_state_id=19
###
GET http://localhost:3001/api/games/start/?room_id=1


###
GET http://localhost:3001/api/games/state/?room_id=1

###
GET http://localhost:3001/rooms/4