POST http://localhost:8080/api/users/login
content-type: application/json

{
  "username": "user1",
  "password": "pass"
}

###

POST http://localhost:8080/api/users/register
content-type: application/json

{
  "username": "user12",
  "password": "pass"
}

###

POST http://localhost:8080/users
content-type: application/json

{
  "username": "user",
  "password": "pass"
}

###

POST http://localhost:3001/api/games/hand
content-type: application/json

{
  "user_id": "1",
  "pickedCard": "4"
}

###

POST http://localhost:3001/api/games/state
content-type: application/json

{
  "room_id": "1"
}

###

POST http://localhost:3001/api/games/state
content-type: application/json

{ 
  "playedCard": "2",
  "room_id": "1"
}

###

POST http://localhost:3001/api/games/round
content-type: application/json

{
  "game_state_id": "1"
}

